name: Auto Deploy to Rumahweb FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          # Folder tujuan di server (CPanel)
          server-dir: ${{ secrets.FTP_PATH }}/

          # Folder yang diupload dari GitHub → hanya folder public/
          local-dir: public

          # File internal sync
          state-name: .ftp-deploy-sync.json

          # Jangan hapus file server setiap deploy
          dangerous-clean-slate: false
