name: Auto Deploy to Rumahweb FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          # Path absolut — WAJIB, supaya tidak bikin public_html baru
          server-dir: ${{ secrets.FTP_PATH }}

          # Folder lokal yang mau diupload
          local-dir: "./"

          # Jangan hapus folder root di server
          dangerous-clean-slate: false
