name: Auto Deploy to Rumahweb FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          # Folder tujuan upload harus diakhiri /
          server-dir: ${{ secrets.FTP_PATH }}/

          # Upload semua file project → termasuk public
          local-dir: "./"

          # Aman, tidak hapus semua file
          dangerous-clean-slate: false

          state-name: ".ftp-deploy-sync.json"
